# Generated by Django 5.2 on 2025-12-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettycashtransaction',
            old_name='petty_cash_fund',
            new_name='fund',
        ),
    ]
