# Generated by Django 5.2 on 2026-01-05 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_document_required_approvers_documentapprover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentapprover',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
