# Generated by Django 5.2 on 2025-12-16 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_pettycashfund_pettycashholder_pettycashtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='holders',
            field=models.ManyToManyField(related_name='petty_cash_funds', to=settings.AUTH_USER_MODEL),
        ),
    ]
