# Generated by Django 5.2 on 2025-12-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pettycashfund_holders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashholder',
            name='fund',
        ),
    ]
