# Generated by Django 5.2 on 2025-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_pettycashfund_holders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashtransaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
