# Generated by Django 5.2 on 2025-12-17 23:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_pettycashtransaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
