# Generated by Django 5.2 on 2025-12-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_document_documentstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentstatus',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterUniqueTogether(
            name='documentstatus',
            unique_together=set(),
        ),
    ]
