# Generated by Django 5.2 on 2026-01-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileRecourse',
            new_name='FileResource',
        ),
        migrations.RenameModel(
            old_name='FolderResourse',
            new_name='FolderResource',
        ),
    ]
