# Generated by Django 5.2 on 2026-01-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0002_alter_folderresource_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comm.folderresource'),
        ),
    ]
