# Generated by Django 5.2 on 2026-01-26 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0002_rename_filerecourse_fileresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileraw',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
