# Generated by Django 5.2 on 2026-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0003_fileresource_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='size',
        ),
        migrations.AddField(
            model_name='fileraw',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
