# Generated by Django 5.2 on 2026-01-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0003_fileraw_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='files',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comm.fileraw'),
        ),
    ]
