# Generated by Django 5.2 on 2026-01-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0004_remove_resourcebase_size_fileraw_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderresource',
            name='file_resources',
        ),
    ]
