# Generated by Django 5.2 on 2026-01-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0004_remove_fileresource_files_fileresource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='extension',
        ),
        migrations.AddField(
            model_name='fileraw',
            name='extension',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
