# Generated by Django 5.2 on 2026-01-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0005_remove_resourcebase_extension_fileraw_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='file',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='files',
            field=models.ManyToManyField(to='comm.fileraw'),
        ),
    ]
