# Generated by Django 5.2 on 2026-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0005_remove_folderresource_file_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileraw',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
    ]
