# Generated by Django 5.2 on 2026-01-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0007_alter_fileraw_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileraw',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8),
        ),
    ]
