# Generated by Django 5.2 on 2026-01-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0008_alter_fileraw_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileraw',
            name='size',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
