# Generated by Django 5.2 on 2025-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin_user', 'Admin_user'), ('common_user', 'Common User')], default='common_user', max_length=15),
        ),
    ]
