# Generated by Django 5.2 on 2026-01-06 00:07

import apps.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.core.utils.validators.PhonenumberValidator()], verbose_name='Phonenumber'),
        ),
    ]
