# Generated by Django 5.2 on 2025-12-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationuser',
            options={'ordering': ('-id',)},
        ),
    ]
