# Generated by Django 5.2 on 2026-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarmallisettings',
            name='journal_author',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
